# Inspired from https://github.com/zapbot/zap-mgmt-scripts/blob/master/.github/workflows/zap-vs-owasp-benchmark.yml

services:
  benchmark:
    build:
      context: ../
      dockerfile: ./VMs/Dockerfile
    ports:
      - 8443:8443

  zap:
    image: ghcr.io/zaproxy/zaproxy
    depends_on:
      - benchmark
    volumes:
      - ./zap/wrk:/zap/wrk/
    command: /zap/wrk/dozap.sh

    